[package]
name = "axum_demo"
version = "0.1.0"
edition = "2021"
rust-version = "1.81"

[dependencies]
axum = "0.8.7"
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.48.0", features = ["full"] }
